### ISSUE TITLE
move transpose operations outside loop

### ISSUE THREAD

**Issue by kurtosis** [Csmith1105/CSC142#1]
Right now the transposes of X and Y are computed in singleThetaUpdate so they're repeated during each iteration step. Since X and Y don't change you can just do them once in main method and store X_T and Y_T as class variables.

https://github.com/Csmith1105/CSC142/blob/789ccdd8d3fdacbc7f6dfd2d0e1953b52d7827c6/H10_christina.java#L182

**Comment by kurtosis** [comment]
Ha I don't know why I didn't think of this before- you don't even need to transpose X and Y! It's kind of wasteful to do so bc all you're doing is copying data into a new matrix w/ the axes flipped.

The transposes x_t and y_t are used in calls to the multiply and subtract arguments. But remember that 
x_t[i][j] == x[j][i]
So you could just add an argument to multiply (and subtract) that is a T/F flag indicating if the second matrix needs to be transposed, and if it is you just flip the indexes in the loop.

**Comment by kurtosis** [comment]
One other thought- I think x, y, theta_init are what's known as class variables (or maybe instance variables). In other words they should be properties of the class, meaning that any method can access them. Look at n_iterations for another example- you use it in one of your methods but you don't need to pass it as an argument. Likewise I think in fitTheta and singleThetaUpdate you shouldn't need to pass x and y as arguments (in fact the code would be clearer if you don't). I'm not entirely sure how Java handles this since they are created by the main method. Maybe you have to use 'public double' instead of 'double' when X and Y are created.

**Comment by Csmith1105** [comment]
Oh yeah, I see what you mean about just flipping the indexes! :)  That's
okay, it was a good exercise for me and helped me better visualize how
nested loops work.

We are just now starting to talk about what classes actually are in the
grand scheme of things.  That's why I didn't really understand what you
were talking about before.  I read Chapter 8 on the flight home and then
our next assignment is about writing a class.
